on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.16.1'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Run Unit tests
        run: cd hello-world && go test ./...
      - run: sam build --use-container
      - env:
          ARTIFACT_S3_BUCKET: arn:aws:s3:::crazy8sdeployments
        run: sam deploy --stack-name crazy-8s-service --s3-bucket $ARTIFACT_S3_BUCKET